/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedMenuRouteImport } from './routes/_authed/menu'
import { Route as AuthedHistoryRouteImport } from './routes/_authed/history'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedBillingRouteImport } from './routes/_authed/billing'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMenuRoute = AuthedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHistoryRoute = AuthedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBillingRoute = AuthedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AuthedBillingRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/history': typeof AuthedHistoryRoute
  '/menu': typeof AuthedMenuRoute
  '/settings': typeof AuthedSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AuthedBillingRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/history': typeof AuthedHistoryRoute
  '/menu': typeof AuthedMenuRoute
  '/settings': typeof AuthedSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/billing': typeof AuthedBillingRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/history': typeof AuthedHistoryRoute
  '/_authed/menu': typeof AuthedMenuRoute
  '/_authed/settings': typeof AuthedSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/billing'
    | '/dashboard'
    | '/history'
    | '/menu'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/billing'
    | '/dashboard'
    | '/history'
    | '/menu'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/billing'
    | '/_authed/dashboard'
    | '/_authed/history'
    | '/_authed/menu'
    | '/_authed/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/menu': {
      id: '/_authed/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthedMenuRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/history': {
      id: '/_authed/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthedHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/billing': {
      id: '/_authed/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthedBillingRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedBillingRoute: typeof AuthedBillingRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedHistoryRoute: typeof AuthedHistoryRoute
  AuthedMenuRoute: typeof AuthedMenuRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBillingRoute: AuthedBillingRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedHistoryRoute: AuthedHistoryRoute,
  AuthedMenuRoute: AuthedMenuRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
